[build]
command = "npm run build-storybook"
publish = "storybook-static"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../../"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"